# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-05 00:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='title',
            field=models.CharField(max_length=32, verbose_name='权限名称'),
        ),
        migrations.AlterField(
            model_name='role',
            name='title',
            field=models.CharField(max_length=32, verbose_name='职位'),
        ),
        migrations.AlterField(
            model_name='user',
            name='pwd',
            field=models.CharField(max_length=32, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(to='CRM.Role', verbose_name='职位'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user',
            field=models.CharField(max_length=32, verbose_name='姓名'),
        ),
    ]
